# Generated by Django 5.1.2 on 2024-10-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_choice_text_alter_passage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='content',
        ),
    ]
